apiVersion: v1
kind: Service
metadata:
  name: igp1-app-service
  labels:
    app: igp1-app
spec:
  type: NodePort
  selector:
    app: igp1-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
